export const PHASES = [
  {
    number: '01',
    title: 'Discovery',
    subtitle: 'Understanding the Problem Through Research',
    color: '#FF6B6B',
    summary: 'Discovery research revealed that student road accidents are not isolated incidents but a recurring behavioral pattern driven by overspeeding, peer influence, low risk perception, and weak enforcement systems.',
    sections: [
      {
        type: 'newspaper',
        title: 'Newspaper Clippings',
        description: 'Real-world cases highlighting the severity and patterns',
        items: [
          {
            source: 'THE TIMES OF INDIA',
            date: 'Jan 2, 2026',
            headline: '2 students among four die in road accidents across city',
            excerpt: 'Hyderabad: Since Wednesday afternoon, four people, including two students and an electrician, have died in separate road accidents in the city.',
            details: 'In Kondapur, a 19-year-old Instacart worker took his brother\'s bike to report for work at around 10:30 pm. While travelling towards Kothagudu, in front of Palapitta Park, he lost control of the two-wheeler.',
          },
          {
            source: 'THE TIMES OF INDIA',
            date: 'Aug 1, 2025',
            headline: '2 students killed in road accidents within 24 hrs in Meerut',
            excerpt: 'Barely: A day after a 10-year-old schoolboy died in a road accident, another student was killed after a speeding govt bus ran over her while she was on her way to college.',
            details: 'Eyewitnesses said the bus allegedly dragged the body of Manisha Singh, a BA student, for about 20 metres before the driver abandoned the vehicle and fled the scene.',
          },
          {
            source: 'THE HINDU',
            date: 'Jan 8, 2026',
            headline: 'Hyderabad: Four students killed, one injured as car crashes near Mirzaguda Gate',
            excerpt: 'Preliminary probe suggests that overspeeding caused the accident near Mirzaguda Gate in Chevella in the early hours of Thursday (January 8, 2026).',
            details: 'The deceased have been identified as Kargayala Sumith, 20, Sri Nikhil, 20, Balmuri Rohith, 18 and Devala Surya Teja, 20.',
          },
          {
            source: 'THE TIMES OF INDIA',
            date: 'Jan 9, 2026',
            headline: 'Telangana horror: 4 students from ICFAI Business School (IBS) die in high-speed car crash',
            excerpt: 'Four students travelling in a car died in a road accident in Mokila late Wednesday night, following a birthday celebration.',
            details: 'According to police, five students were travelling in an SUV when the vehicle hit a tree at high speed. Authorities are yet to determine whether drunk driving was a factor.',
          },
          {
            source: 'THE FEDERAL',
            date: 'Feb 13, 2026',
            headline: 'Hoskote accident: How a joyride at dawn turned deadly for 6 students',
            excerpt: 'According to police sources, the group of youths had gone out for a "jolly ride", consumed biryani, and was driving towards Nandi Hills when the accident happened.',
            details: 'The SUV involved in the accident was registered in the name of the deceased student Ari\'s father.',
          },
        ],
      },
      {
        type: 'research',
        title: 'Key Research Findings',
        description: 'Insights from secondary research and case analysis',
        items: [
          {
            insight: 'Knowledge Gap',
            finding: 'Students know road rules but still violate them',
            impact: 'Awareness alone is insufficient to change behavior',
          },
          {
            insight: 'Speeding Prevalence',
            finding: 'Overspeeding is a major contributor to accidents',
            impact: '70% of student accidents involve excessive speed',
          },
          {
            insight: 'Peer Influence',
            finding: 'Driving behavior is heavily influenced by friends',
            impact: 'Social acceptance overrides personal safety concerns',
          },
          {
            insight: 'Risk Perception',
            finding: 'Youth underestimate accident likelihood',
            impact: 'Students believe accidents only happen to "other people"',
          },
        ],
      },
    ],
  },
  {
    number: '02',
    title: 'Empathy',
    subtitle: 'Understanding Student Perspectives',
    color: '#4ECDC4',
    summary: 'Empathy research showed that students often understand the rules but make unsafe decisions because of social pressure, overconfidence, emotions, convenience, and cultural norms.',
    sections: [
      {
        type: 'interviews',
        title: 'Student & Expert Interviews',
        description: 'Direct insights from students and professionals',
        items: [
          {
            type: 'student',
            name: 'Arjun Reddy',
            role: 'Engineering Student (Age 20)',
            quote: 'My friends take the risk, so I feel pressure to do the same. But I know it\'s dangerous.',
            insights: [
              'Wants to fit in with peer group',
              'Acknowledges risk but feels social pressure',
              'Overconfident in driving skills',
              'Doesn\'t believe "it will happen to me"',
            ],
          },
          {
            type: 'student',
            name: 'Priya Sharma',
            role: 'Business Student (Age 19)',
            quote: 'Everyone speeds. It\'s become normal. Slow driving feels boring compared to what my friends do.',
            insights: [
              'Risk normalization through peer behavior',
              'Thrill-seeking and excitement motivation',
              'Safety perception influenced by cultural norms',
              'Social status associated with risky behavior',
            ],
          },
          {
            type: 'student',
            name: 'Sree Sanjana',
            role: 'Medtech Student (Age 21)',
            quote: 'I know the consequences intellectually, but emotionally, in the moment, you don\'t think about it.',
            insights: [
              'Gap between knowledge and action',
              'Emotional decision-making overrides logic',
              'Moment-based impulsivity',
              'Disconnect from real-world consequences',
            ],
          },
          {
            type: 'expert',
            name: 'Dr. Meera Sharma',
            role: 'Clinical Psychologist (Age 42)',
            expertise: 'Youth Risk Behavior & Decision Making',
            insights: [
              'Risk normalization: Students see risky behavior as "normal" because peers do it',
              'Overconfidence bias: Youth overestimate their abilities and control',
              'Thrill-seeking: Adolescent neurochemistry drives sensation-seeking',
              'Peer pressure: Social acceptance matters more than safety',
              'Emotional decision-making: Logic takes backseat to emotions',
              'Status perception: Risky driving is seen as cool, confident, mature',
            ],
          },
        ],
      },
      {
        type: 'personas',
        title: 'Proto Personas',
        description: 'Archetypes representing key stakeholders',
        items: [
          {
            name: 'Arjun Reddy',
            role: 'Student Rider',
            age: 20,
            goals: ['Maintain social status', 'Enjoy freedom and independence', 'Keep up with peer group'],
            frustrations: ['Social pressure to take risks', 'Fear of being left out', 'Overconfidence leads to risky decisions'],
            needs: ['Peer acceptance without endangering life', 'Practical understanding of real consequences', 'Alternative ways to feel confident'],
            motivations: ['Social belonging', 'Thrill and excitement', 'Personal autonomy'],
          },
          {
            name: 'Parent',
            role: 'Guardian & Protector',
            age: 45,
            goals: ['Child\'s safety and well-being', 'Responsible behavior development', 'Peace of mind'],
            frustrations: ['Cannot monitor child constantly', 'Weak enforcement of road safety', 'Limited accountability mechanisms'],
            needs: ['Systems that encourage responsibility', 'Real consequences and accountability', 'Child\'s awareness of real dangers'],
            motivations: ['Protecting loved ones', 'Building lifelong safe habits', 'Parental responsibility'],
          },
          {
            name: 'Traffic Psychologist',
            role: 'Safety Expert',
            age: 42,
            goals: ['Reduce accident rates', 'Change driving culture', 'Implement systemic solutions'],
            frustrations: ['Awareness campaigns don\'t change behavior', 'Weak enforcement', 'Lack of accountability systems'],
            needs: ['Behavioral intervention strategies', 'Accountability mechanisms', 'Real-world consequence communication'],
            motivations: ['Public safety', 'Evidence-based solutions', 'Cultural transformation'],
          },
        ],
      },
    ],
  },
  {
    number: '03',
    title: 'Define',
    subtitle: 'Identifying the Root Causes',
    color: '#FFD93D',
    summary: 'The Define phase revealed that road safety is fundamentally a behavioral and cultural challenge rather than simply an awareness problem.',
    sections: [
      {
        type: 'rootcause',
        title: 'Root Cause Analysis',
        description: 'Five major root causes identified',
        items: [
          {
            id: 1,
            title: 'Risky Driving Behaviors Are Normalized',
            statement: 'Students often see overspeeding, wrong-way driving, and negligent behavior as "normal" because their peers do it.',
            whyTree: [
              'Why students engage in risky behavior: They see peers doing it without immediate consequences',
              'Why peers normalize it: Social groups reinforce risky behavior as acceptable',
              'Why enforcement is weak: Police often don\'t catch violators in time',
              'Root Cause: Risky driving has become normalized in student culture',
            ],
          },
          {
            id: 2,
            title: 'Student Decision-Making Is Influenced by Bias and Overconfidence',
            statement: 'Students underestimate accident risks and overestimate their own driving skills due to psychological biases.',
            whyTree: [
              'Why students don\'t believe accidents can happen: Overconfidence bias makes them think they\'re better drivers',
              'Why risk perception is low: "It only happens to other people" mentality',
              'Why emotional decisions override logic: In-the-moment adrenaline overrides rational thinking',
              'Root Cause: Students know rules but don\'t believe consequences apply to them',
            ],
          },
          {
            id: 3,
            title: 'Inadequate Road Safety Education and Real-Life Exposure',
            statement: 'Current safety education lacks real-world impact and doesn\'t translate knowledge into behavior change.',
            whyTree: [
              'Why education doesn\'t work: Students already know the rules, awareness isn\'t the issue',
              'Why students feel invincible: No real exposure to serious consequences',
              'Why lectures fail: Abstract information doesn\'t create emotional impact',
              'Root Cause: Missing educational models that create behavioral change',
            ],
          },
          {
            id: 4,
            title: 'Weak Adoption of Safety Gear and Vehicle Responsibility',
            statement: 'Students neglect helmets, don\'t maintain vehicles, and don\'t feel ownership of safety responsibilities.',
            whyTree: [
              'Why helmets aren\'t worn: Seen as uncool or inconvenient',
              'Why vehicles aren\'t maintained: Students don\'t feel responsible for their own or borrowed vehicles',
              'Why safety gear is skipped: Peer pressure and cultural perception override safety',
              'Root Cause: Low accountability and missing sense of ownership',
            ],
          },
          {
            id: 5,
            title: 'Poor Monitoring, Enforcement, and Accountability Systems',
            statement: 'Existing enforcement mechanisms are insufficient, inconsistent, and don\'t create lasting behavioral change.',
            whyTree: [
              'Why students violate rules: Enforcement is rare and inconsistent',
              'Why penalties are ineffective: They\'re reactive, not preventive',
              'Why accountability is weak: No system tracks repeat violators or vehicle condition',
              'Root Cause: Absence of continuous monitoring and accountability framework',
            ],
          },
        ],
      },
      {
        type: 'statement',
        title: 'Problem Statement',
        description: 'Core challenge',
        content: 'University students continue to experience a high rate of road accidents because risky driving behaviors are normalized, consequences are underestimated, safety education lacks real-world impact, and accountability systems are weak. This challenges the education system, parents, and road authorities to develop systemic behavioral interventions.',
      },
    ],
  },
  {
    number: '04',
    title: 'Ideation',
    subtitle: 'Exploring Opportunities for Change',
    color: '#A8E6CF',
    summary: 'The ideation process generated 192 solutions. After evaluation, the Tiered Driving License Test System linked with vehicle maintenance compliance emerged as the most comprehensive solution.',
    sections: [
      {
        type: 'hmw',
        title: 'How Might We Questions',
        description: 'Six strategic opportunity areas',
        items: [
          {
            number: '1',
            question: 'How might we reduce the normalization of risky driving behaviors among university students?',
            focus: 'Cultural Change',
          },
          {
            number: '2',
            question: 'How might we enable students to make safer decisions despite social, emotional, and environmental pressures?',
            focus: 'Decision Support',
          },
          {
            number: '3',
            question: 'How might we transform road safety from a rule-following activity into a valued part of student identity and culture?',
            focus: 'Identity Integration',
          },
          {
            number: '4',
            question: 'How might we make safe driving more rewarding and socially respected than risky driving among university students?',
            focus: 'Social Incentives',
          },
          {
            number: '5',
            question: 'How might we help students recognize and understand the real-life consequences of unsafe driving before accidents occur?',
            focus: 'Consequence Awareness',
          },
          {
            number: '6',
            question: 'How might we create a continuous system of accountability that encourages responsible driving and vehicle maintenance among students?',
            focus: 'Accountability System',
          },
        ],
      },
      {
        type: 'brainwriting',
        title: 'Brainwriting (8-3-8 Method)',
        description: 'Systematic ideation process results',
        stats: {
          participants: 8,
          rounds: 8,
          ideasPerPersonPerRound: 3,
          totalIdeas: 192,
        },
        featured: {
          title: 'Top Solution',
          solution: 'Tiered Driving License Test System Linked to Vehicle Maintenance Compliance',
          description: 'A comprehensive framework that combines progressive licensing with vehicle responsibility, creating accountability at multiple touchpoints.',
          why: 'Addresses behavior change, accountability, vehicle responsibility, and systemic cultural shift simultaneously.',
        },
      },
    ],
  },
];
